
GET https://localhost:4000/account_balance
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidG90YWwiOjMwMDAwMCwiaWF0IjoxNzM1Mzk4MzA5fQ.4jfe8YkhW5NlAnD9bfSn-kYVp1ddjTuXSZt5GrQkxX0



POST https://localhost:4000/paying_order
Content-Type: application/json

{
    "id" : 1,
    "total": 300000
}